CREATE TABLE PROJECTS_REDCAP_OUTPUT_EAV (
	SYSID NUMBER NOT NULL ENABLE, 
	PROJECTID NUMBER, 
	PATIENT_NUM NUMBER, 
	STUDYID VARCHAR2(50 BYTE), 
	EVENT_NAME VARCHAR2(255 BYTE), 
	VAR VARCHAR2(255 BYTE), 
	VALUE CLOB, 
	SENDLOG VARCHAR2(2000 BYTE), 
	GENERATED CLOB
);


CREATE TABLE PROJECTS_XLS_EAV (
	SESSIONID NUMBER, 
	PATIENTNUM NUMBER, 
	LEVEL_CD NUMBER, 
	STARTING DATE, 
	ENDING DATE, 
	CONCEPTS CLOB, 
	VAL CLOB, 
	DATES CLOB
);

CREATE INDEX IDX_SESSION_ID ON PROJECTS_XLS_EAV (SESSIONID) ;

CREATE TABLE PROJECTS_XLS_EXP_FIELDS (
	SYSID NUMBER, 
	PROJECTID NUMBER, 
	USERNAME VARCHAR2(35 BYTE), 
	CONCEPT_NAME VARCHAR2(512 BYTE), 
	CONCEPT_PATH VARCHAR2(512 BYTE), 
	OPTIONS VARCHAR2(255 BYTE), 
	AGGR VARCHAR2(50 BYTE), 
	MODIFIER VARCHAR2(100 BYTE), 
	PRIMARY KEY (SYSID)
);

CREATE TABLE PROJECTS_XLS_EXP_JOBS (
	SESSIONID NUMBER, 
	USERNAME VARCHAR2(35 BYTE), 
	PROJECTID NUMBER, 
	PROJECTCODE VARCHAR2(35 BYTE), 
	RESULT_INSTANCE_ID NUMBER, 
	PATIENT_LIST_DESC VARCHAR2(255 BYTE), 
	STATUS VARCHAR2(25 BYTE), 
	DATECOMPLETED DATE, 
	OPTIONS VARCHAR2(255 BYTE), 
	LASTMOST_SHEET BLOB, 
	PRIMARY KEY (SESSIONID)
);