GRANT SELECT ON i2b2demodata.concept_dimension to I2B2MART"projectcode";
GRANT SELECT ON i2b2demodata.observation_fact to I2B2MART"projectcode";
GRANT SELECT ON I2B2DEMODATA.provider_dimension to I2B2MART"projectcode";
DROP TABLE I2B2MART"projectcode".observation_fact;
CREATE VIEW I2B2MART"projectcode".OBSERVATION_FACT AS SELECT O.* FROM i2b2demodata.observation_fact o, I2B2MART"projectcode".patient_dimension where o.patient_num=patient_dimension.patient_num;
DROP TABLE I2B2MART"projectcode".provider_dimension;
CREATE SYNONYM I2B2MART"projectcode".provider_dimension FOR I2B2DEMODATA.provider_dimension;
INSERT INTO i2b2MART"projectcode".concept_dimension select * from I2B2DEMODATA.concept_dimension;
INSERT INTO I2B2PM.pm_project_data( PROJECT_ID, PROJECT_NAME, PROJECT_PATH,STATUS_CD) VALUES('"projectcode"','"projectcode" Project','/"projectcode"','A');
CREATE TABLE I2B2MART"projectcode".ONT_PROCESS_STATUS AS SELECT ONT_PROCESS_STATUS.* FROM i2b2metadata.ONT_PROCESS_STATUS;
CREATE TABLE I2B2MART"projectcode".TABLE_ACCESS AS SELECT TABLE_ACCESS.* FROM i2b2metadata.TABLE_ACCESS;
CREATE TABLE I2B2MART"projectcode".SCHEMES AS SELECT SCHEMES.* FROM i2b2metadata.SCHEMES;
GRANT SELECT ON i2b2metadata.i2b2 TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.medispan TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.flowsheets TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.ICD10_ICD9 TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.zipcodes TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.smartdata TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.social_hx TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.micro TO I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.mar to I2B2MART"projectcode";
GRANT SELECT ON i2b2metadata.medispan_w_mar to I2B2MART"projectcode";
CREATE SYNONYM I2B2MART"projectcode".i2b2 FOR i2b2metadata.i2b2;
CREATE SYNONYM I2B2MART"projectcode".ICD10_ICD9 FOR i2b2metadata.ICD10_ICD9;
CREATE SYNONYM I2B2MART"projectcode".medispan FOR i2b2metadata.medispan;
CREATE SYNONYM I2B2MART"projectcode".medispan_w_mar for i2b2metadata.medispan_w_mar;
CREATE SYNONYM I2B2MART"projectcode".zipcodes FOR i2b2metadata.zipcodes;
CREATE SYNONYM I2B2MART"projectcode".flowsheets FOR i2b2metadata.flowsheets;
CREATE SYNONYM I2B2MART"projectcode".smartdata FOR i2b2metadata.smartdata;
CREATE SYNONYM I2B2MART"projectcode".social_hx FOR i2b2metadata.social_hx;
CREATE SYNONYM I2B2MART"projectcode".micro FOR i2b2metadata.micro;
INSERT INTO I2B2PM.pm_project_user_roles( PROJECT_ID, USER_ID, USER_ROLE_CD,STATUS_CD) VALUES( '"projectcode"','AGG_SERVICE_ACCOUNT','USER','A');
INSERT INTO I2B2PM.pm_project_user_roles( PROJECT_ID, USER_ID, USER_ROLE_CD,STATUS_CD) VALUES( '"projectcode"','AGG_SERVICE_ACCOUNT','MANAGER','A');
INSERT INTO I2B2PM.pm_project_user_roles( PROJECT_ID, USER_ID, USER_ROLE_CD,STATUS_CD) VALUES( '"projectcode"','AGG_SERVICE_ACCOUNT','DATA_OBFSC','A');
INSERT INTO I2B2PM.pm_project_user_roles( PROJECT_ID, USER_ID, USER_ROLE_CD,STATUS_CD) VALUES( '"projectcode"','AGG_SERVICE_ACCOUNT','DATA_AGG','A');